---
title: "HW6_Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---

```{r setup}
knitr::opts_chunk$set(warning = F)
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
library(htmlwidgets)
```

```{r load_data}
instacart = 
  read_csv("./data/orders_train_allvars.csv") %>%
  clean_names() %>%
  filter(department %in% c("bakery", "deli", "frozen", "produce")) %>%
  select(department, product_name, order_dow, order_hour_of_day, aisle ) 
```

Column {.sidebar}
-----------------------------------------------------------------------

This `flexdashboard` with Shiny was made for P8105 Data Science I - HW6 Interactivity Project. The data come from “The Instacart Online Grocery Shopping Dataset 2017”.  Download the data used for this app [here](http://jeffgoldsmith.com/DSI/data/instacart_train_data.csv.zip)

```{r radioButtons_widget}
dow = c( "sunday", "monday",  "tuesday", "wednesday",  "thursday",  "friday",  "saturday")

selectInput("day_of_week", label = h3("Select Day of Week"),
            choices = dow, selected = "sunday")
```


```{r  selectInput_widget}
department = c("bakery", "deli", "frozen", "produce")
radioButtons("Department", label = h4("Select Department"),
            choices = department, selected = "bakery")
```



Row
-----------------------------------------------------------------------

### Chart A Bar graph of most popular product in each deparment

```{r}
renderPlotly({ 
instacart %>%
    group_by(department, order_dow) %>%
    mutate(orders = n()) %>%
    mutate(most_popular = product_name[which.max(orders)],
           orders = max(orders)) %>%
    ungroup(order_dow) %>%
    mutate(order_dow = recode(order_dow,"0" = "sunday", "1" = "monday", "2" = "tuesday", "3" = "wednesday", "4" = "thursday", "5" = "friday", "6" = "saturday")) %>%
    mutate(most_popular = fct_reorder(most_popular, orders)) %>%
    filter(order_dow == input$day_of_week) %>%
    plot_ly( x = ~most_popular, y = ~orders, color = ~department, type = "bar")
})

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B Box plot of the hour of the day the order was placed on across department

```{r}
renderPlotly({ 
 instacart %>%
  group_by(aisle) %>%
  mutate(iqr_hr_of_day = IQR(order_hour_of_day)) %>% 
  ungroup(aisle) %>% 
  mutate(aisle = forcats::fct_reorder(aisle,iqr_hr_of_day)) %>%
  group_by(aisle) %>% 
  filter(department == input$Department) %>%
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "box",
          colors = "Set2")

})

```

### Chart C Bar graph number of orders placed during a week

```{r}
renderPlotly({ 
 instacart %>% 
  group_by(department, order_dow) %>%
  mutate(orders = n()) %>%
  ungroup() %>%
  mutate(order_dow = as.factor(order_dow)) %>%
  mutate(order_dow = recode(order_dow,"0" = "sunday", "1" = "monday", "2" = "tuesday", "3" = "wednesday", "4" = "thursday", "5" = "friday", "6" = "saturday")) %>% 
  group_by(order_dow) %>%
  filter(department == input$Department) %>%
  plot_ly(y = ~orders, x = ~order_dow, color = ~department, type = "bar",
          colors = "Set3")
})

```

